### ISSUE TITLE
Day68 : Wrong answers

### ISSUE THREAD

**Issue by dhanendraverma** [vaskoz/dailycodingproblem-go#747]
@vaskoz 
The code fails for the following input :
( (0,0), (1,4), (2,2), (0,1), (4,0), (2,3), (4,4) )
Code output - 3
Right ans - 5

**Comment by vaskoz** [comment]
Hi @dhanendraverma , thanks for suggesting another testcase. I added your testcase to my existing solution but I believe the correct answer is 6. Your input creates the following chessboard, assuming tuples are (row, col).

```
x x . . .
. . . . x
. . x x .
. . . . .
x . . . x
```
A logging line shows which bishop tuples attack each other. Recall, the problem states that bishops can attack each other "through pieces".
> On our special chessboard, two bishops attack each other if they share the same diagonal. This includes bishops that have another bishop located between them, i.e. bishops can attack through pieces.

From the problem statement https://github.com/vaskoz/dailycodingproblem-go/issues/145

```
{0 0} {2 2}
{0 0} {4 4}
{1 4} {2 3}
{2 2} {4 0}
{2 2} {4 4}
{0 1} {2 3}
```

I added your testcase and expected output of 6 to my testcases with this commit. https://github.com/vaskoz/dailycodingproblem-go/commit/c3ee50999194305ca2cf3fa47acc6ff103e70874 Please let me know if you see something wrong with my explanation.

**Comment by dhanendraverma** [comment]
Hey @vaskoz! yes, you're right, the correct answer would be 6 for the above test case.

Thanks for considering the suggestion and improvements.
